### ISSUE TITLE
Move to /xing

### ISSUE THREAD

**Issue by ralph** [xing/typhoeus#13]
Hey Stefan!

I had trouble finding this repos, as it was neither present in our internal Github nor on github.com/xing. Would you mind moving it to /xing, for better findability?

You should be able to transfer here:
https://github.com/skaes/typhoeus/settings
<img width="740" alt="bildschirmfoto 2015-07-06 um 10 00 54" src="https://cloud.githubusercontent.com/assets/2190/8517955/fead243c-23c5-11e5-809f-987d1713d704.png">

Thanks! :)

Regards
Ralph

**Comment by boosty** [comment]
I think it's a good idea :+1:

**Comment by skaes** [comment]
Done. Remember: with great power come great responsibility.

**Comment by boosty** [comment]
Cool! I also changed the default branch to 'xing'.

**Comment by ralph** [comment]
Thank you! :)
